version: "3.4"
services:

  voip-carrier-simulator:
    build:
      context: .
    restart: always      
    network_mode: host
    volumes:
     - ./conf/srv/etc/asterisk/extensions.conf:/srv/etc/asterisk/extensions.conf
